namespace: team1
resources:
  - namespace.yaml
  - rbac.yaml
bases:
  - ../../base/flux/
patchesStrategicMerge:
  - flux-patch.yaml
configMapGenerator:
  - name: flux-kube-config
    behavior: replace
    files:
      - kubeconfig.yaml
