resources:
  - account.yaml
  - role.yaml
  - git-key.yaml
  - deployment.yaml
configMapGenerator:
  - name: flux-kube-config
    files:
      - kubeconfig.yaml
images:
  - name: fluxcd/flux
    newTag: 1.15.0
